### ISSUE TITLE
Agent.onClose not called when ErrorHandler closes AgentRunner

### ISSUE THREAD

**Issue by jheusser** [real-logic/Agrona#65] opened 2016-05-25 09:24 UTC
This might be by design or my weird usage, but if the `ErrorHandler` closes its own `AgentRunner` then `onClose` of `Agent` is not called on close.

Example code here https://gist.github.com/jheusser/1cb33999f281e5a7719a07ad158bbb21

**Comment by mjpt777** [comment] 2016-05-25 10:53
In your example you are closing the agent before started it. By doing this it will not enter the run loop and thus never reach `onClose()` because `running` will be false. So the question is how can a error handler be called before something is running? Unless I'm missing something the example is very contrived.

https://github.com/real-logic/Agrona/blob/master/src/main/java/org/agrona/concurrent/AgentRunner.java#L102

**Comment by jheusser** [comment] 2016-05-27 07:45
The example might not be too obvious, but the `SomeAgent` does run `doWork` once invoked by the `AgentRunner`, then throws an exception which invokes the `RunOnError` error handler. Only then the error handler closes the `AgentRunner`, which does not run `onClose` of its agents.

**Comment by mjpt777** [comment] 2016-05-27 10:55
What am I missing? In the example you give close is called before the agent is schedule to run.

**Comment by jheusser** [comment] 2016-05-27 11:08
I am starting to doubt myself but I think what you are referring to is passing the close method to the error handler, but it is not invoking it, it just sets it as Runnable:
https://gist.github.com/jheusser/1cb33999f281e5a7719a07ad158bbb21#file-agenttest-java-L47

The close is only invoked on the first error.

**Comment by mjpt777** [comment] 2016-05-27 11:37
Sorry I missed that. I'll have a proper look this week and debug this.

**Comment by mjpt777** [comment] 2016-05-28 10:39
Rather than me being silly and just reading the code I ran it this time. Duh! I can see what the issue is now. The Agent was never closed in your example. If you change the main to be like the below then it works.

```java
    public static void main(String[] args) throws Exception
    {
        RunOnError closeOnError = new RunOnError();

        AgentRunner agentRunner = new AgentRunner(new BusySpinIdleStrategy(), closeOnError, null, new SomeAgent());

        closeOnError.action(agentRunner::close);

        AgentRunner.startOnThread(agentRunner);

        agentRunner.close();
    }
```

**Closed** 2016-06-21 17:33 UTC
