### ISSUE TITLE
ManyToOneConcurrentArrayQueue poll may return null when queue isEmpty() is false

### ISSUE THREAD

**Issue by wireknight** [real-logic/agrona#269] opened 2022-11-26 20:57 UTC
To my understanding from the javadoc, poll() should be consistent with isEmpty() return value and thus should never return null is if isEmpty returns false. Using the snippet below I observed a different behaviour

```
import java.io.Serializable;
import java.util.Objects;
import org.agrona.concurrent.ManyToOneConcurrentArrayQueue;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.atomic.AtomicBoolean;

public class AgroTest {
    public static void main(String[] args) {
        ManyToOneConcurrentArrayQueue<TestMsg> queue = new ManyToOneConcurrentArrayQueue<>(1000);
        AtomicBoolean finished = new AtomicBoolean(false);
        long msgsToSend = 1_000_000_000;
        ForkJoinPool.commonPool().execute(() -> {
            TestMsg payload = new TestMsg("TestMe", new Payload(0xdeadbeef));
            for (long element = 0; element < msgsToSend; element++) {
                queue.offer(payload);
            }
            finished.setRelease(true);
        });
        while(!finished.getAcquire() || !queue.isEmpty()) {
            while(!queue.isEmpty()) {
                Objects.requireNonNull(queue.poll());
            }
        }
    }
    private record Payload(int value) implements Serializable {}
    private record TestMsg(String name, Payload payload) implements Serializable {}
}

```

Output:

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at io.reacted.examples.benchmarking.AgroTest.main(AgroTest.java:34)
```

**Comment by mjpt777** [comment] 2022-11-27 07:32
Duplicate of https://github.com/real-logic/agrona/issues/216

**Closed by mjpt777** 2022-11-27 07:32 UTC
